Feature/text form field component
DonateDonate/gather-here-Flutter pull request #14
Opened 2024-08-14 06:47 UTC by spicypunch

- [ ] TextFormFieldComponent 구현
- [ ] DesignScreen에 예제 화면 생성

2024-08-14 10:23 UTC, FirstDo requested changes
종맴 굿

피그마에보면 별도의 title가지는 친구들도 있거든요
로그인 페이지보면, "아이디", "비밀번호" 이런 Text도 같이 포함인데
이친구가 이거까지 같이 커버할 수 있었으면 좋을것 같아요

![스크린샷 2024-08-14 오후 7 22 50](https://github.com/user-attachments/assets/6240098e-ad7f-4eac-92ec-0c23111c231c)

optional로 입력받아서 해당 값있으면 그려지게

2024-08-14 10:23 UTC, FirstDo commented on lib/common/components/default_text_form_field.dart
> +              borderRadius: BorderRadius.circular(widget.radius)),
P1 - focusedBorder는 color black으로 해주세요!

2024-08-14 10:23 UTC, FirstDo commented on lib/common/components/default_text_form_field.dart
> +import 'package:flutter/cupertino.dart';
P2 - 이거 안쓰고있네요 삭제 고고

2024-08-14 10:23 UTC, FirstDo commented on lib/common/components/default_text_form_field.dart
> +import 'package:flutter/widgets.dart';
P2 - 이것도 안쓰고있네요 삭제 고고

2024-08-14 10:23 UTC, FirstDo commented on lib/common/components/default_text_form_field.dart
> +  final void Function(String)? onChanged; // 입력된 텍스트가 수정될  호출되는 콜백
P3 - typedef를 쓰는게 가독성 면에서 좀 더 낫지 않나 싶습니다

-> ValueChanged<String>?

2024-08-14 10:23 UTC, FirstDo commented on lib/common/components/default_text_form_field.dart
> +  final String? Function(String?)? validator; // 텍스트 입력 검증
P3 - 얘도 마찬가지로

=> FormFieldValidator<String>?

2024-08-14 13:48 UTC, spicypunch commented on lib/common/components/default_text_form_field.dart
> +  final void Function(String)? onChanged; // 입력된 텍스트가 수정될  호출되는 콜백
키보드 타입 말하는 거죠?

2024-08-15 10:09 UTC, FirstDo approved these changes

2024-08-16 05:08 UTC, merged